templates = {
    'credicoop' : {
        'path':r'pdf\credicoop\test.pdf',
        'output_path':r'csv\credicoop\credicoop.csv',
        'area':[24,0,92,100], 
        'columns':[11,17,55,67,85,100],
        'labels':['Fecha','ID','Descripcion','Debito','Credito','Saldo'],
        'pages':14,
        'first_page_length':35,
        'last_page_length':51
        },
    'galicia':{
        'path':r'pdf\galicia\test.pdf',
        'output_path':r'csv\galicia\galicia.csv',
        'area':[12,0,95,100], 
        'columns':[13,46,64,82,100],
        'labels':['Fecha','Descripcion','Credito','Debito','Saldo'],
        'pages':2,
        'first_page_length':51,
        'last_page_length':55
        },
    'supervielle':{
        'path':r'pdf\supervielle\test.pdf',
        'output_path':r'csv\supervielle\supervielle.csv',
        'area':[24,0,91,100], 
        'columns':[11,17,55,67,85,100],
        'labels':['Fecha','ID','Descripcion','Debito','Credito','Saldo'],
        'pages':15,
        'first_page_length':35,
        'last_page_length':51
        },
    'provincia':{
        'path':r'pdf\provincia\test.pdf',
        'output_path':r'csv\provincia\provincia.csv',
        'area':[20,0,95,100], 
        'columns':[10,55,73,82,100],
        'labels':['Fecha','Descripcion','Importe','Fecha Valor','Saldo'],
        'pages':39,
        'first_page_length':20,
        'last_page_length':67
        },
    'mercadopago':{
        'path':r'pdf\mercadopago\test.pdf',
        'output_path':r'csv\mercadopago\mercadopago.csv',
        'area':[10,0,85,100], 
        'columns':[15,46,61,81,100],
        'labels':['Fecha','Descripcion','ID','Valor','Saldo'],
        'pages':320,
        'first_page_length':33,
        'last_page_length':67
        },
}